# Generated by Django 3.0.6 on 2020-05-19 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('founded_year', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('total_funding', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stage', models.CharField(max_length=100)),
                ('category', models.ManyToManyField(to='tracxn_scraper.Category')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_angel', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Investor',
                'verbose_name_plural': 'Investors',
            },
        ),
        migrations.CreateModel(
            name='NewsLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracxn_scraper.Company')),
            ],
            options={
                'verbose_name': 'NewsLink',
                'verbose_name_plural': 'NewsLinks',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='investor',
            field=models.ManyToManyField(to='tracxn_scraper.Investor'),
        ),
    ]
