# Generated by Django 3.0.6 on 2020-05-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracxn_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='stage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='total_funding',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
