# Generated by Django 3.0.6 on 2020-05-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=50)),
                ('profile_photo_url', models.URLField(null=True)),
                ('employed_date', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['employed_date'],
            },
        ),
    ]
