# Generated by Django 3.0.6 on 2020-05-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
